### PR TITLE
[WIP] task to push pre-commit configuration

### PR DESCRIPTION
**Pull request by sbidoul**
WIP, towards #80

### CODE REVIEW

**Comment by Yajo** [comment]
Hi there. I'm going to go a little yes-but-no off-topic here.

Recently I've been co-developing https://github.com/pykong/copier and although it could still have a couple of bugs, it's working pretty well.

I think it would be much better for us to have a Copier template project for OCA repo.

Then, a cron GH action could just walk all OCA's repos in all main branches and run `copier --force update && git add . && git commit -m update && git push` (sort of).

Benefits:

1. Easy to understand and to maintain project templates.
1. Easy to reproduce bugs by local CLI.
1. The resulting bot could even be a standard GH action also. Maybe @pykong would like to develop it, as it would be beneficial for OCA but for any other organization too.
1. We don't only use pre-commit. We use travis, codecov, GH actions (in the future; see #67), runbot... And it's impossible to predict what we'll be using in the future. Having a proper template system would let us evolve properly.
1. Templates are versioned.

**Comment by sbidoul** [comment]
> I think it would be much better for us to have a Copier template project for OCA repo.

@Yajo we can try this. Do we need a new repo for the template then?

**Comment by Yajo** [comment]
> Do we need a new repo for the template then?

Yes, that would be best.

**Comment by Yajo** [comment]
@sbidoul Are you gonna participate in next week's code sprint? It could be a good occasion to work together in all of this. :thinking:

**Comment by sbidoul** [comment]
@Yajo I did not know there was a code sprint next week. Not sure I'll have much available time. When is that taking place?

**Comment by pedrobaeza** [comment]
It's supposed that @JordiBForgeFlow should notify board about it...

https://www.aeodoo.org/event/spanish-oca-days-2020-2020-05-18-2020-05-19-60/register
https://docs.google.com/document/d/1z8jFY9fWgdUCFER9y6no_uQmsg2p5FDN4NHmtxa3FDw/edit#

**Pull request closed without merging**
