### PR TITLE
exclude comments from matched commands + test

### PR DESCRIPTION
**Pull request by SimoRubi**
Closing #82

### CODE REVIEW

**Comment by SimoRubi** [comment]
> /ocabot merge (inception?)

yes, inception :smile:

**Comment by pedrobaeza** [comment]
It's still not deployed in the server I suppose cc @sbidoul

**Comment by SimoRubi** [comment]
@sbidoul either this is not working, or it isn't deployed yet.
I hope very much the latter!

**Comment by sbidoul** [comment]
> > /ocabot merge (inception?)
> 
> yes, inception smile

Now it's deployed, let's see.

**Pull request merged**
