### PR TITLE
[WIP] Add squash options

### LINKED ISSUE #43: merge bot: allow to squash commits of the PR
Include a command for squashing the commits of the pull request independently from the fixup! message in them (not everyone makes this properly).

### PR DESCRIPTION
**Pull request by dreispt**
Closes #43﻿

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @dreispt 

Is it still WIP ? Did you planned to work on this again ?

kind regards.

**Comment by dreispt** [comment]
I didn't have time to get back to it. You're free to take over if you like.
There is a git command to do the squash: `git merge --squash`
I'm not sure about the commit message. We should be able to provide it to the ocabot command, and then use that in a git command.

**Comment by Yajo** [comment]
I think a good option would be to use`--autosquash` by default.

This way we let the OP push new commits instead of force-pushing all the time. It makes life easier for reviewers, and still lets to have one or many commits properly formed.

**Comment by mmequignon** [comment]
@dreispt Is this PR still alive? I'd like to take it over if you don't have time to finish this. Thanks!

**Comment by legalsylvain** [comment]
@mmequignon : feel free to work on that topic !

**Comment by SirTakobi** [comment]
@mmequignon any news on this? Thanks!

**Comment by mmequignon** [comment]
> @mmequignon any news on this? Thanks!

I'm really sorry, haven't found time to work on this.
I mostly struggled trying to set up a testing environment.
But it's still smth I have to deal with :)

**Pull request closed without merging**
