### PR TITLE
improve command parser

### LINKED ISSUE #53: merge bot: parse command inside a greater message
For now, the merge bot only reacts to the merge command putting that comment in an isolated message (example of greater message: https://github.com/OCA/account-invoicing/pull/552#issuecomment-507203903).

### PR DESCRIPTION
**Pull request by sbidoul**
closes #53

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And what about messages like
``` 
Great contribution, thanks!

/ocabot merge
```
?

**Comment by pedrobaeza** [comment]
Well, more this one (the previous one was covered):
``` 
Great contribution, thanks!

/ocabot merge

Please forward port it to 12.0.
```

**Comment by sbidoul** [comment]
@pedrobaeza should be ok.

**Comment by sbidoul** [comment]
deployed

**Pull request merged**
