### PR TITLE
Add merging label while merging a PR

### LINKED ISSUE #73: merge bot: It would be nice to have a tag 'merging' applied on PRs with a merge process in progress

### PR DESCRIPTION
**Pull request by guewen**
Closes #73

### CODE REVIEW

**Comment by sbidoul** [comment]
@guewen would you mind rebasing this? There is a conflict (sorry) following a rework of subprocess calls for better error handling and Sentry support. It should be quite easy.

**Comment by legalsylvain** [comment]
@sbidoul I just rebased the @guewen branch.

regards.

**Comment by sbidoul** [comment]
Thanks @legalsylvain. I'm going to merge this.

The fact the the removal of the merge label has to be done at 4 different places and I don't see an easy way to do it better is another sign that this merge bot needs a heavy refactoring...

**Comment by sbidoul** [comment]
This is deployed and works fine. Example in https://github.com/OCA/mis-builder/pull/254. Thanks @guewen

**Comment by lmignon** [comment]
Great!!! Thank you all.

**Pull request merged**
